# Nicholas Yue yue.nicholas@gmail.com

MESSAGE ( "DEBUGGING FindHDK $HT = " $ENV{HT})
IF ( $ENV{HT} MATCHES "toolkit" )

  INCLUDE_DIRECTORIES ( $ENV{HT}/include )

  EXECUTE_PROCESS ( COMMAND hcustom -g -c OUTPUT_VARIABLE DEBUG_TEMP_DEFINITIONS )
  EXECUTE_PROCESS ( COMMAND hcustom -c OUTPUT_VARIABLE TEMP_DEFINITIONS )
  EXECUTE_PROCESS ( COMMAND hcustom -m OUTPUT_VARIABLE TEMP_LINK_FLAGS )

  MESSAGE ( "DEBUG_TEMP_DEFINITIONS = " ${DEBUG_TEMP_DEFINITIONS} )
  MESSAGE ( "TEMP_DEFINITIONS = " ${TEMP_DEFINITIONS} )
  MESSAGE ( "TEMP_LINK_FLAGS = " ${TEMP_LINK_FLAGS} )

  STRING ( STRIP ${TEMP_LINK_FLAGS}  HDK_LINK_FLAGS )

  ADD_DEFINITIONS (
	-DMAKING_DSO
	)

  IF (WIN32)
	
	# Release flags
	STRING ( REGEX REPLACE "-DVERSION=\"[0-9]+.[0-9]+.[0-9]+\" " "" HDK_DEFINITIONS "${TEMP_DEFINITIONS}")
	SET ( CMAKE_C_FLAGS ${HDK_DEFINITIONS})
	SET ( CMAKE_CXX_FLAGS ${HDK_DEFINITIONS})
	
	# Debug flags
	STRING ( REGEX REPLACE "Making DEBUG version" "" STRIP_TEMP_DEFINITIONS "${DEBUG_TEMP_DEFINITIONS}")
	STRING ( REGEX REPLACE "-DVERSION=\"[0-9]+.[0-9]+.[0-9]+\" " "" DEBUG_HDK_DEFINITIONS "${STRIP_TEMP_DEFINITIONS}")
	SET ( CMAKE_C_FLAGS_DEBUG ${DEBUG_HDK_DEFINITIONS})
	SET ( CMAKE_CXX_FLAGS_DEBUG ${DEBUG_HDK_DEFINITIONS})
	
	ADD_DEFINITIONS ( /D_CRT_SECURE_NO_DEPRECATE /wd4996 )

	FILE ( GLOB DSOLIB_A $ENV{HFS}/custom/houdini/dsolib/*.a )
	FILE ( GLOB DSOLIB_LIB $ENV{HFS}/custom/houdini/dsolib/*.lib )
	LINK_DIRECTORIES ($ENV{HFS}/custom/houdini/dsolib )
	MESSAGE ( "DSOLIB_A = " ${DSOLIB_A})
	MESSAGE ( "DSOLIB_LIB = " ${DSOLIB_LIB})
    SET ( HDK_LIBRARIES ${DSOLIB_LIB} ${DSOLIB_A} )
  ELSE (WIN32)

	# Release flags
	STRING ( REGEX REPLACE "-DVERSION=..[0-9]+.[0-9]+.[0-9]+.. " "" HDK_DEFINITIONS "${TEMP_DEFINITIONS}")
	
	# Debug flags
	STRING ( REGEX REPLACE "Making debug version" "" STRIP_TEMP_DEFINITIONS "${DEBUG_TEMP_DEFINITIONS}")
	STRING ( REGEX REPLACE "-DVERSION=..[0-9]+.[0-9]+.[0-9]+.. " "" DEBUG_HDK_DEFINITIONS "${STRIP_TEMP_DEFINITIONS}")
	
	IF (CMAKE_BUILD_TYPE MATCHES Debug)
      ADD_DEFINITIONS ( ${DEBUG_HDK_DEFINITIONS})
	ELSE (CMAKE_BUILD_TYPE MATCHES Debug)
      ADD_DEFINITIONS ( ${HDK_DEFINITIONS})
	ENDIF (CMAKE_BUILD_TYPE MATCHES Debug)

	LINK_DIRECTORIES (${HDK_LIBRARY_DIRS} )
	
  ENDIF (WIN32)
  
  FUNCTION(GenerateSESITagSourceFile filename)
    EXECUTE_PROCESS ( COMMAND date OUTPUT_VARIABLE DATE )
    EXECUTE_PROCESS ( COMMAND hostname OUTPUT_VARIABLE HOSTNAME )
    SET ( SESITAG_STR "compiled on: " ${DATE} "         by: " $ENV{LOGNAME} "@" ${HOSTNAME} )
	FILE ( WRITE ${CMAKE_BINARY_DIR}/tmp_sesitag.C ${SESITAG_STR} )
	FILE ( WRITE ${CMAKE_BINARY_DIR}/sesitag.sh "#!/bin/sh\nsesitag -m < tmp_sesitag.C")
	EXECUTE_PROCESS ( COMMAND sh ${CMAKE_BINARY_DIR}/sesitag.sh OUTPUT_VARIABLE SESITAG_OUTPUT )
	MESSAGE ( "SESITAG_OUTPUT = " ${SESITAG_OUTPUT} )

	STRING ( REPLACE "-DUT_DSO_TAGINFO='\"" "" TEMP_UT_DSO_TAGINFO ${SESITAG_OUTPUT})
	MESSAGE ( "TEMP_UT_DSO_TAGINFO = " ${TEMP_UT_DSO_TAGINFO} )
	STRING ( REPLACE "\"'" "" UT_DSO_TAGINFO ${TEMP_UT_DSO_TAGINFO})
	MESSAGE ( "UT_DSO_TAGINFO = " ${UT_DSO_TAGINFO} )


    FILE ( WRITE ${filename} "//\n")
    FILE ( APPEND ${filename} "// Warning: do not edit, this file was written automatically by FindHDK.cmake.\n")
    FILE ( APPEND ${filename} "//\n")
#    FILE ( APPEND ${filename} "#ifdef __UT_DSOVersion__\n")
#    FILE ( APPEND ${filename} "#undef  __UT_DSOVersion__\n")
#    FILE ( APPEND ${filename} "#endif\n")
    FILE ( APPEND ${filename} "#define UT_DSO_TAGINFO \"" ${UT_DSO_TAGINFO} "\"\n")
    FILE ( APPEND ${filename} "#include <UT/UT_DSOVersion.h>\n")




  ENDFUNCTION()
  
  SET ( HDK_FOUND TRUE )
  SET ( HDK_HIH_DIR $ENV{HIH})
  MESSAGE ( "HDK_HIH_DIR = " ${HDK_HIH_DIR} )
ENDIF ()
