# Nicholas Yue yue.nicholas@gmail.com

MESSAGE ( "DEBUGGING FindHDK $HT = " $ENV{HT})
IF ( $ENV{HT} MATCHES "toolkit" )

  INCLUDE_DIRECTORIES ( $ENV{HT}/include )

  EXECUTE_PROCESS ( COMMAND hcustom -g -c OUTPUT_VARIABLE DEBUG_TEMP_DEFINITIONS )
  EXECUTE_PROCESS ( COMMAND hcustom -c OUTPUT_VARIABLE TEMP_DEFINITIONS )
  EXECUTE_PROCESS ( COMMAND hcustom -m OUTPUT_VARIABLE TEMP_LINK_FLAGS )

  MESSAGE ( "DEBUG_TEMP_DEFINITIONS = " ${DEBUG_TEMP_DEFINITIONS} )
  MESSAGE ( "TEMP_DEFINITIONS = " ${TEMP_DEFINITIONS} )
  MESSAGE ( "TEMP_LINK_FLAGS = " ${TEMP_LINK_FLAGS} )

  STRING ( STRIP ${TEMP_LINK_FLAGS}  HDK_LINK_FLAGS )

  IF (WIN32)
	
	# Release flags
	STRING ( REGEX REPLACE "-DVERSION=\"[0-9]+.[0-9]+.[0-9]+\" " "" HDK_DEFINITIONS "${TEMP_DEFINITIONS}")
	SET ( CMAKE_C_FLAGS ${HDK_DEFINITIONS})
	SET ( CMAKE_CXX_FLAGS ${HDK_DEFINITIONS})
	
	# Debug flags
	STRING ( REGEX REPLACE "Making DEBUG version" "" STRIP_TEMP_DEFINITIONS "${DEBUG_TEMP_DEFINITIONS}")
	STRING ( REGEX REPLACE "-DVERSION=\"[0-9]+.[0-9]+.[0-9]+\" " "" DEBUG_HDK_DEFINITIONS "${STRIP_TEMP_DEFINITIONS}")
	SET ( CMAKE_C_FLAGS_DEBUG ${DEBUG_HDK_DEFINITIONS})
	SET ( CMAKE_CXX_FLAGS_DEBUG ${DEBUG_HDK_DEFINITIONS})
	
	ADD_DEFINITIONS ( /D_CRT_SECURE_NO_DEPRECATE /wd4996 )

	FILE ( GLOB DSOLIB_A $ENV{HFS}/custom/houdini/dsolib/*.a )
	FILE ( GLOB DSOLIB_LIB $ENV{HFS}/custom/houdini/dsolib/*.lib )
	LINK_DIRECTORIES ($ENV{HFS}/custom/houdini/dsolib )
	
  ELSE (WIN32)

	ADD_DEFINITIONS (
	  -DMAKING_DSO
	  )
	# Release flags
	STRING ( REGEX REPLACE "-DVERSION=..[0-9]+.[0-9]+.[0-9]+.. " "" HDK_DEFINITIONS "${TEMP_DEFINITIONS}")
	
	# Debug flags
	STRING ( REGEX REPLACE "Making debug version" "" STRIP_TEMP_DEFINITIONS "${DEBUG_TEMP_DEFINITIONS}")
	STRING ( REGEX REPLACE "-DVERSION=..[0-9]+.[0-9]+.[0-9]+.. " "" DEBUG_HDK_DEFINITIONS "${STRIP_TEMP_DEFINITIONS}")
	
	IF (CMAKE_BUILD_TYPE MATCHES Debug)
      ADD_DEFINITIONS ( ${DEBUG_HDK_DEFINITIONS})
	ELSE (CMAKE_BUILD_TYPE MATCHES Debug)
      ADD_DEFINITIONS ( ${HDK_DEFINITIONS})
	ENDIF (CMAKE_BUILD_TYPE MATCHES Debug)

	LINK_DIRECTORIES (${HDK_LIBRARY_DIRS} )
	
  ENDIF (WIN32)
  
  
  SET ( HDK_FOUND TRUE )
  
ENDIF ()
